version: "3.9"

services:
    database:
        image: timescale/timescaledb:latest-pg14
        container_name: voyager-1
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=core
        volumes:
            - pgdata:/data/postgres

    redis:
        image: redis:alpine
        container_name: voyager_cache
        restart: always
        ports:
            - 6380:6379

volumes:
    pgdata:
        driver: local
